```{r, include = FALSE}
source(here::here("/data/environment_vars.R"))
knitr::read_chunk("ch_06_01_data.R")
```


# Spatial Dependence

We'll check for spatial dependence in our data using Correlograms (plots of distance vs. Moran's I)

```{r correlogram_response, cache=FALSE, include = FALSE}
```
```{r correlogram_quadratic, cache=FALSE, include = FALSE}
```
```{r correlogram_plots, cache=FALSE, include = FALSE}
```

A Correlogram of the predictor: elevation

```{r, include = FALSE}
gg_correlogram_elev
```



```{r, include = FALSE}
gg_correlogram_resid_1
```





<!-- # Aspatial model building {.tabset} -->

<!-- Let's try three aspatial **logistic regression models**: -->

<!-- We'll use three different sets of predictors. -->

<!-- ## Elevation -->
<!-- <div class="fold s o"> -->
<!-- ```{r model_1_center, class.source='klippy'} -->
<!-- ``` -->
<!-- </div> -->



<!-- ## Elevation, slope, aspect -->
<!-- <div class="fold s o"> -->
<!-- ```{r model_2_center, class.source='klippy'} -->
<!-- ``` -->
<!-- </div> -->




<!-- ## Quadratic elevation -->
<!-- <div class="fold s o"> -->
<!-- ```{r model_3_center, class.source='klippy'} -->
<!-- ``` -->
<!-- </div> -->


<!-- # Aspatial Model Diagnostics -->

<!-- In this example, I'm including only some **very** basice model diagnostics: residual plots.  I'm also going to proceed as if the diagnostics were totally fine.  In a real analysis, you'd want to perform a more thorough set of model diagnostics. -->


<!-- Here's a very nice article about plotting residuals with ggplot:  -->
<!-- <a href="https://drsimonj.svbtle.com/visualising-residuals">Visualising Residuals by Simon Jackson</a> -->

<!-- The following are simple base R plots: -->

<!-- ## Elevation Model -->

<!-- Elevation vs residuals and predicted vs. residuals plots for model 1:  -->

<!-- <div class="fold s"> -->
<!-- ```{r model_1_diagnostics} -->
<!-- ``` -->
<!-- </div> -->


<!-- ## Quadratic Elevation Model -->

<!-- We'll only plot the predicted vs. residuals plot here.  Since this model has mutliple predictors plotting predictors vs. residuals is more complicated. -->

<!-- <div class="fold s"> -->
<!-- ```{r model_3_diagnostics} -->
<!-- ``` -->
<!-- </div> -->

