---
title: "Multiscale Analysis of Forest Cover"
output: 
  # pdf_document:
    # toc: yes
  html_document:
    css: css/styles.css
    number_sections: TRUE
    toc: true
    toc_float: true
---


```{r setup, include = FALSE, echo = FALSE}
tmp = rprojroot::find_rstudio_root_file()
knitr::opts_chunk$set(root.dir = tmp, error = TRUE)
knitr::opts_knit$set(echo = TRUE, error = TRUE, root.dir = tmp)
source(paste0(tmp, "/data/environment_vars.R"))
require(raster)
require(rgdal)
require(rgeos)
rm(tmp)
```

# Illustration with site 1
```{r}

b1 = 1e3
b2 = 5e3

bf1 = buffer(sites[1, ], width = b1)
bf2 = buffer(sites[1, ], width = b2)

# zoom() won't work if there is not a plot window open
plot(0, type = "n")
zoom(nlcd, bf1)
zoom(nlcd, bf1, legend = F, axes = F, col = terrain.colors(5))
zoom(nlcd, bf2, legend = F, axes = F, col = terrain.colors(5))


plot(bf1, add = T)
points(sites, pch = 19, cex = 2,  add = TRUE)

# dev.off() is your friend
dev.off()

# crop is fast, mask is slow.
# mask keeps the original raster extent.
# if you crop first, you only have to mask a small raster

# mask is much slower than crop:
t1 = proc.time()
m1 = mask(forest, bf1)
elapsed = proc.time() - t1
elapsed

t1 = proc.time()
m2 = crop(forest, bf1)
elapsed = proc.time() - t1
elapsed

plot(crop(m1, bf1))
plot(m2)

plot(mask(crop(forest, bf1), bf1))
plot(mask(crop(forest, bf2), bf2))
```
<div class="red">
Note:  The crop and mask code on page 37 won't do what you want...
</div>


